-- Write your PostgreSQL query statement below
SELECT C.NAME AS CUSTOMERS
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.ID = O.CUSTOMERID
WHERE O.ID IS NULL;

-- SELECT NAME AS CUSTOMERS
-- FROM CUSTOMERS
-- WHERE ID NOT IN (SELECT DISTINCT CUSTOMERID FROM ORDERS); -- 217 ms